### ISSUE TITLE
method access to node attributes (node.foo.bar) is deprecated

### ISSUE THREAD

**Issue by cullenmcdermott** [mthssdrbrg/kafka-cookbook#104]
When running the cookbook with recent versions of chef the following warning pops up at the end of the run
```
Deprecated features used!
         "method access to node attributes (node.foo.bar) is deprecated and will be removed in Chef 13, please use bracket syntax (node["foo"]["bar"]) at 66 locations:
           - /tmp/kitchen/cache/cookbooks/java/attributes/default.rb:22:in `from_file'
           - /tmp/kitchen/cache/cookbooks/kafka/libraries/helpers.rb:100:in `broker_attribute?'
           - /tmp/kitchen/cache/cookbooks/kafka/recipes/_defaults.rb:14:in `from_file'
           - /tmp/kitchen/cache/cookbooks/kafka/recipes/_defaults.rb:16:in `from_file'
           - /tmp/kitchen/cache/cookbooks/kafka/recipes/_defaults.rb:22:in `from_file'
           - /tmp/kitchen/cache/cookbooks/kafka/recipes/_defaults.rb:23:in `from_file'
           - /tmp/kitchen/cache/cookbooks/kafka/recipes/_defaults.rb:26:in `from_file'
           - /tmp/kitchen/cache/cookbooks/kafka/recipes/_defaults.rb:27:in `from_file'
           - /tmp/kitchen/cache/cookbooks/kafka/recipes/_setup.rb:6:in `from_file'
           - /tmp/kitchen/cache/cookbooks/kafka/recipes/_setup.rb:10:in `from_file'
           - /tmp/kitchen/cache/cookbooks/kafka/recipes/_setup.rb:11:in `block in from_file'
           - /tmp/kitchen/cache/cookbooks/kafka/recipes/_setup.rb:18:in `from_file'
           - /tmp/kitchen/cache/cookbooks/kafka/recipes/_setup.rb:19:in `from_file'
           - /tmp/kitchen/cache/cookbooks/kafka/recipes/_setup.rb:20:in `from_file'
           - /tmp/kitchen/cache/cookbooks/kafka/recipes/_setup.rb:23:in `block (2 levels) in from_file'
           - /tmp/kitchen/cache/cookbooks/kafka/recipes/_setup.rb:24:in `block (2 levels) in from_file'
           - /tmp/kitchen/cache/cookbooks/kafka/libraries/helpers.rb:91:in `kafka_log_dirs'
           - /tmp/kitchen/cache/cookbooks/kafka/libraries/helpers.rb:92:in `kafka_log_dirs'
           - /tmp/kitchen/cache/cookbooks/kafka/libraries/helpers.rb:93:in `kafka_log_dirs'
           - /tmp/kitchen/cache/cookbooks/kafka/libraries/helpers.rb:7:in `kafka_base'
           - /tmp/kitchen/cache/cookbooks/kafka/libraries/helpers.rb:31:in `kafka_download_uri'
           - /tmp/kitchen/cache/cookbooks/kafka/recipes/_install.rb:8:in `block in from_file'
           - /tmp/kitchen/cache/cookbooks/kafka/recipes/_install.rb:9:in `block in from_file'
           - /tmp/kitchen/cache/cookbooks/kafka/recipes/_install.rb:14:in `block in from_file'
           - /tmp/kitchen/cache/cookbooks/kafka/recipes/_install.rb:17:in `block in from_file'
           - /tmp/kitchen/cache/cookbooks/kafka/recipes/_install.rb:22:in `from_file'
           - /tmp/kitchen/cache/cookbooks/kafka/libraries/helpers.rb:19:in `kafka_target_path'
           - /tmp/kitchen/cache/cookbooks/kafka/recipes/_configure.rb:6:in `from_file'
           - /tmp/kitchen/cache/cookbooks/kafka/recipes/_configure.rb:7:in `block in from_file'
           - /tmp/kitchen/cache/cookbooks/kafka/recipes/_configure.rb:8:in `block in from_file'
           - /tmp/kitchen/cache/cookbooks/kafka/recipes/_configure.rb:13:in `from_file'
           - /tmp/kitchen/cache/cookbooks/kafka/recipes/_configure.rb:15:in `block in from_file'
           - /tmp/kitchen/cache/cookbooks/kafka/recipes/_configure.rb:16:in `block in from_file'
           - /tmp/kitchen/cache/cookbooks/kafka/recipes/_configure.rb:19:in `block in from_file'
           - /tmp/kitchen/cache/cookbooks/kafka/libraries/helpers.rb:80:in `restart_on_configuration_change?'
           - /tmp/kitchen/cache/cookbooks/kafka/recipes/_configure.rb:25:in `from_file'
           - /tmp/kitchen/cache/cookbooks/kafka/recipes/_configure.rb:27:in `block in from_file'
           - /tmp/kitchen/cache/cookbooks/kafka/recipes/_configure.rb:28:in `block in from_file'
           - /tmp/kitchen/cache/cookbooks/kafka/recipes/_configure.rb:31:in `block in from_file'
           - /tmp/kitchen/cache/cookbooks/kafka/libraries/helpers.rb:35:in `kafka_init_style'
           - /tmp/kitchen/cache/cookbooks/kafka/recipes/_configure.rb:55:in `block in from_file'
           - /tmp/kitchen/cache/cookbooks/kafka/recipes/_configure.rb:56:in `block in from_file'
           - /tmp/kitchen/cache/cookbooks/kafka/recipes/_configure.rb:58:in `block in from_file'
           - /tmp/kitchen/cache/cookbooks/kafka/recipes/_configure.rb:59:in `block in from_file'
           - /tmp/kitchen/cache/cookbooks/kafka/recipes/_configure.rb:69:in `from_file'
           - /tmp/kitchen/cache/cookbooks/kafka/libraries/helpers.rb:76:in `start_automatically?'
           - /tmp/kitchen/cache/cookbooks/kafka/recipes/_setup.rb:7:in `block (2 levels) in from_file'
           - /tmp/kitchen/cache/cookbooks/kafka/recipes/_setup.rb:14:in `block (2 levels) in from_file'
           - /tmp/kitchen/cache/cookbooks/kafka/libraries/helpers.rb:27:in `kafka_installed?'
           - /tmp/kitchen/cache/cookbooks/kafka/libraries/helpers.rb:23:in `kafka_jar_path'
           - /tmp/kitchen/cache/cookbooks/kafka/attributes/default.rb:181:in `block in from_file'
           - /tmp/kitchen/cache/cookbooks/kafka/attributes/default.rb:154:in `block in from_file'
           - /tmp/kitchen/cache/cookbooks/kafka/attributes/default.rb:172:in `block in from_file'
           - /tmp/kitchen/cache/cookbooks/kafka/attributes/default.rb:163:in `block in from_file'
           - (erubis):1:in `block in evaluate'
           - /tmp/kitchen/cache/cookbooks/kafka/libraries/env_file.rb:14:in `export?'
           - (erubis):2:in `block in evaluate'
           - (erubis):4:in `block in evaluate'
           - (erubis):5:in `block in evaluate'
           - (erubis):6:in `block in evaluate'
           - (erubis):7:in `block in evaluate'
           - (erubis):8:in `block in evaluate'
           - (erubis):9:in `block in evaluate'
           - (erubis):11:in `block in evaluate'
           - (erubis):13:in `block in evaluate'
           - /tmp/kitchen/cache/cookbooks/kafka/libraries/helpers.rb:114:in `fetch_broker_attribute'
```

**Comment by mthssdrbrg** [comment]
Oh, wow, I was not aware about this at all, thanks for pointing it out. I've switched to bracket syntax in #106.
