### ISSUE TITLE
broker_id too long 

### ISSUE THREAD

**Issue by jianchen2580** [mthssdrbrg/kafka-cookbook#113]
no working to kafka 0.10.0.1, because the broker_id is too long. 
```
unless broker_attribute?(:broker, :id)
  node.default.kafka.broker.broker_id = node.ipaddress.gsub('.', '').to_i % 2**31
end
```

**Comment by jianchen2580** [comment]
reserved.broker.max.id = 1000
```
java.lang.IllegalArgumentException: requirement failed: broker.id must be equal or greater than -1 and not greater than reserved.broker.max.id
       	at scala.Predef$.require(Predef.scala:233)
       	at kafka.server.KafkaConfig.validateValues(KafkaConfig.scala:998)
       	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:994)
       	at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:743)
       	at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:740)
       	at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.scala:28)
       	at kafka.Kafka$.main(Kafka.scala:58)
       	at kafka.Kafka.main(Kafka.scala)
```

**Comment by mthssdrbrg** [comment]
Yeah, there's a workaround for Kafka >= `0.9.x.y`, but unfortunately it's only described in the [release notes for `v0.9.0`](https://github.com/mthssdrbrg/kafka-cookbook/releases/tag/v0.9.0) (of this cookbook). In short explicitly set `node['kafka']['broker']['broker.id']` to `nil` and it should work (i.e. Kafka will generate an ID for you). The same applies to `node['kafka']['broker']['port']` as well.

There should probably be an entry in the README about this.

**Comment by mthssdrbrg** [comment]
@jianchen2580: since I haven't heard anything more I'm going to assume that the workaround worked for you, and close this. If it didn't, please reopen.
