### ISSUE TITLE
no implicit conversion of nil into String

### ISSUE THREAD

**Issue by joshskains** [mthssdrbrg/kafka-cookbook#146]
================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/kafka/recipes/default.rb
================================================================================

TypeError
---------
no implicit conversion of nil into String

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/kafka/recipes/_service.rb:6:in `from_file'
  /var/chef/cache/cookbooks/kafka/recipes/default.rb:10:in `from_file'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/kafka/recipes/_service.rb:

  1:  #
  2:  # Cookbook Name:: kafka
  3:  # Recipe:: _service
  4:  #
  5:  
  6>> template kafka_init_opts[:env_path] do
  7:    source 'env.erb'
  8:    owner 'root'
  9:    group 'root'
 10:    mode '644'
 11:    helpers(Kafka::EnvFile)
 12:    if restart_on_configuration_change?
 13:      notifies :create, 'ruby_block[coordinate-kafka-start]', :immediately
 14:    end
 15:  end

System Info:
------------
chef_version=13.7.16
platform=centos
platform_version=7.0.1406
ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
program_name=chef-client worker: ppid=21837;start=16:19:16;
executable=/opt/chef/bin/chef-client

Running handlers:
[2018-02-20T16:19:24-05:00] ERROR: Running exception handlers
Running handlers complete
[2018-02-20T16:19:24-05:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 08 seconds
[2018-02-20T16:19:25-05:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2018-02-20T16:19:25-05:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-02-20T16:19:25-05:00] ERROR: no implicit conversion of nil into String
[2018-02-20T16:19:25-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by joshskains** [comment]
Figured it out. Mistake by me. My apologies.
