### ISSUE TITLE
md5 is not case sensitive

### ISSUE THREAD

**Issue by spuder** [mthssdrbrg/kafka-cookbook#81]
The md5 provided by kafka is now entirely upper case. If you provide a md5 sum with uppper case letters, the download will fail. 

For example, with 8.2.1 the md5 is

     446eab1f5329eb03662926aa1cb0845d

Changing one or more letters to uppercase will throw the following error. 

```
           ================================================================================
           Error executing action `create` on resource 'kafka_download[/tmp/kitchen/cache/kafka_2.10-0.8.2.1.tgz]'
           ================================================================================

           SystemExit
           ----------
           ruby_block[kafka-validate-download] (/tmp/kitchen/cookbooks/kafka/providers/download.rb line 20) had an error: SystemExit: exit

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cookbooks/kafka/providers/download.rb:24:in `block (3 levels) in class_from_file'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cookbooks/kafka/recipes/_install.rb

             6: kafka_download kafka_local_download_path do
             7:   source kafka_download_uri(kafka_tar_gz)
             8:   checksum node.kafka.checksum
             9:   md5_checksum node.kafka.md5_checksum
            10:   not_if { kafka_installed? }
            11: end
            12:

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cookbooks/kafka/recipes/_install.rb:6:in `from_file'

           kafka_download("/tmp/kitchen/cache/kafka_2.10-0.8.2.1.tgz") do
             action :create
             updated true
             updated_by_last_action true
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :kafka_download
             cookbook_name :kafka
             recipe_name "_install"
             source "https://archive.apache.org/dist/kafka/0.8.2.1/kafka_2.10-0.8.2.1.tgz"
             checksum "89ede9ae0f51f7163c4140d8ab43fcedf8eb3066bb8058f3d97f75e9868899ce"
             md5_checksum "446eab1f5329eb03662926aa1cb0845D"
             mode "644"
             not_if { #code block }
           end


       Running handlers:
       [2015-04-03T21:29:08+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2015-04-03T21:29:08+00:00] ERROR: Exception handlers complete
       [2015-04-03T21:29:08+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       Chef Client failed. 18 resources updated in 76.431007827 seconds
       [2015-04-03T21:29:08+00:00] ERROR: kafka_download[/tmp/kitchen/cache/kafka_2.10-0.8.2.1.tgz] (kafka::_install line 6) had an error: SystemExit: ruby_block[kafka-validate-download] (/tmp/kitchen/cookbooks/kafka/providers/download.rb line 20) had an error: SystemExit: exit
       [2015-04-03T21:29:08+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by mthssdrbrg** [comment]
Fixed by #82.
